include $(GOROOT)/src/Make.$(GOARCH)

TARG=taipei
GOFILES=\
	bitset.go\
	files.go\
        metainfo.go\
        peer.go\
        torrent.go\
        upnp.go\
	webstatus.go\
        dht.go\
        krpc.go\

include $(GOROOT)/src/Make.pkg
