include $(GOROOT)/src/Make.$(GOARCH)

TARG=taipei
GOFILES=\
	dht_node.go\
        bitset.go\
        files.go\
        metainfo.go\
        peer.go\
        torrent.go\
        upnp.go
include $(GOROOT)/src/Make.pkg
